apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: realtimechat/authentication-service
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: DATABASE_URL
              value: postgresql://User_Service:npg_iHUbkJ1sDB6L@ep-wild-river-a154rapw-pooler.ap-southeast-1.aws.neon.tech/User_Service_Database?sslmode=require&channel_binding=require
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: authentication-service

